# Generated by Django 5.2.3 on 2025-08-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_populate_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="PK of a Plan",
                        help_text="PK of a Plan",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Name of the plan",
                        help_text="Name of the plan",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_comment="Description of the plan",
                        help_text="Description of the plan",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date of the plan",
                        help_text="Creation date of the plan",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_comment="FK to Patient",
                        help_text="FK to Patient",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="user.patient",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        db_comment="FK to Professional",
                        help_text="FK to Professional",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="user.professional",
                    ),
                ),
            ],
        ),
    ]
